### ISSUE TITLE
Addon won't load files with capital letters on win 32

### ISSUE THREAD

**Issue by mills32** [Yethiel/re-volt-addon#24]
So the addon will show a lot of errors if you try to load any file using capital letters (nearly all .PRM files are using them), renaming the files to rpm makes the addon load the files.

**Comment by Yethiel** [comment]
RVGL doesn't support uppercase letters in file names on Linux so I never came across this problem. I'll see if I can implement it in a friendly way. For now I'd like to encourage you to keep all file names lowercase.
